---
title: "Homework 4"
output:
  html_document: 
    toc: true
    toc_float: true
---

### Context

This assignment reinforces ideas in [Interactivity](topic_interactivity.html). 

### Due date and submission

Due: November 1 at 4:00pm. 

Please submit (via courseworks) the web address of the GitHub repo containing your work for this assignment; git commits after the due date will cause the assignment to be considered late.

R Markdown documents included as part of your solutions must not install packages, and should only load the packages necessary for your submission to knit. 

### Points

| Problem         | Points    |
|:--------------- |:--------- |
| Problem 0       | 20        |
| Problem 1       | 40        |
| Problem 2       | 40        |
| Optional survey | No points |


### Problem 0

This "problem" focuses on structure of your submission, especially the use git and GitHub for reproducibility, R Projects to organize your work, R Markdown to write reproducible reports, relative paths to load data from local files (if necessary), and reasonable naming structures for your files. 

To that end: 

* create a public GitHub repo + local R Project for this assignment
* submit a link to your repo via Courseworks

Your solutions to Problems 1 and 2 should be implemented in your .Rmd file(s), and your git commit history should reflect the process you used to solve these Problems. 

For Problem 0, we will assess adherence to the instructions above regarding repo structure, git commit history, and whether we are able to knit your .Rmd to ensure that your work is reproducible. Adherence to appropriate styling and clarity of code will be assessed in Problems 1+ using the homework [style rubric](homework_style_rubric.html). 

This homework includes figures; the readability of your embedded plots (e.g. font sizes, axis labels, titles) will be assessed in Problems 1+.


### Problem 1

Create a personal website at `<YOUR_GH_NAME>.github.io` (or some other reasonably-named location). This page can be as extensive as you'd like, but it should include at least:

* A brief introductory landing page
* A page giving your academic and professional experience (i.e. a resume)
* Links in the site navigation for your GitHub account, your email, and any other professional networks. 


### Problem 2

Create a flexdashboard using `plotly` for that includes at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.). Use one of the following datasets, and load from the `p8105.datasets` package:

* [Instacart](dataset_instacart.html)
* [NY NOAA](dataset_noaa.html)
* [NYC Restaurant Inspections](dataset_restaurant_inspections.html)

These datasets are large; you may want / need to filter or randomly sample from the complete dataset to ensure a reasonable product.

### Optional post-assignment survey

If you'd like, a you can complete [this short survey]() after you've finished the assignment.