---
title: "Homework 3"
output:
  html_document: 
    toc: true
    toc_float: true
---

### Context

This assignment reinforces ideas in [Visualization and EDA](topic_visualization_and_eda.html). 

### Due date and submission

Due: October 14 at 4:00pm. 

Please submit (via courseworks) the web address of the GitHub repo containing your work for this assignment; git commits after the due date will cause the assignment to be considered late.

R Markdown documents included as part of your solutions must not install packages, and should only load the packages necessary for your submission to knit. 


### Points

| Problem         | Points    |
|:--------------- |:--------- |
| Problem 0       | 25        |
| Problem 1       | 25        |
| Problem 2       | 25        |
| Problem 3       | 25        |
| Optional survey | No points |


### Problem 0

This "problem" focuses on structure of your submission, especially the use git and GitHub for reproducibility, R Projects to organize your work, R Markdown to write reproducible reports, relative paths to load data from local files, and reasonable naming structures for your files. 

To that end: 

* create a public GitHub repo + local R Project; we suggest naming this repo / directory `p8105_hw2_YOURUNI` (e.g. `p8105_hw2_ajg2202` for Jeff), but that's not required
* create a single .Rmd file named `p8105_hw2_YOURUNI.Rmd` that renders to `github_document`
* create a subdirectory to store the local data files used in Problems 1 and 2, and use relative paths to access these data files
* submit a link to your repo via Courseworks

Your solutions to Problems 1, 2, and 3 should be implemented in your .Rmd file, and your git commit history should reflect the process you used to solve these Problems. 

For this Problem, we will assess adherence to the instructions above regarding repo structure, git commit history, and whether we are able to knit your .Rmd to ensure that your work is reproducible. Adherence to appropriate styling and clarity of code will be assessed in Problems 1+ using the [style rubric](homework_style_rubric.html).

**This homework includes figures; the readability of your embedded plots (e.g. font sizes, axis labels, titles) will be assessed in Problems 1+.**

### Problem 1 

This problem uses the [Instacart](dataset_instacart.html) data. DO NOT include this dataset in your local data directory; instead, load the data from the [`p8105.datasets`](https://github.com/P8105/p8105.datasets) using:

```{r, eval = FALSE}
library(p8105.datasets)
data("instacart")
```

The goal is to do some exploration of this dataset. To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illstrative examples of observations. Then, do or answer the following (commenting on the results of each):

* How many aisles are there, and which aisles are the most items ordered from? 
* Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it. 
* Make a table showing the three most popular items **in each of the aisles** "baking ingredients", "dog food care", and "packaged vegetables fruits". Include the number of times each item is ordered in your table.
* Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).


### Problem 2

This problem uses the [BRFSS](dataset_brfss.html) data. DO NOT include this dataset in your local data directory; instead, load the data from the [`p8105.datasets`](https://github.com/P8105/p8105.datasets) package. 

First, do some data cleaning: 

* format the data to use appropriate variable names; 
* focus on the "Overall Health" topic
* include only responses from "Excellent" to "Poor" 
* organize responses as a factor taking levels **ordered** from "Poor" to "Excellent"

Using this dataset, do or answer the following (commenting on the results of each):

* In 2002, which states were observed at 7 or more locations? What about in 2010?
* Construct a dataset that is limited to `Excellent` responses, and contains, year, state, and a variable that averages the `data_value` across locations within a state. Make a "spaghetti" plot of this average value over time within a state (that is, make a plot showing a line for each state across years -- the `geom_line` geometry and `group` aesthetic will help).
* Make a two-panel plot showing, for the years 2006, and 2010, distribution of `data_value` for responses ("Poor" to "Excellent") among locations in NY State. 


### Problem 3

Accelerometers have become an appealing alternative to self-report techniques for studying physical activity in observational studies and clinical trials, largely because of their relative objectivity. During observation periods, the devices measure "activity counts" in a short period; one-minute intervals are common. Because accelerometers can be worn comfortably and unobtrusively, they produce around-the-clock observations.

This problem uses five weeks of accelerometer data collected on a 63 year-old male with BMI 25, who was admitted to the Advanced Cardiac Care Center of Columbia University Medical Center and diagnosed with congestive heart failure (CHF). The data can be downloaded [here](./data/accel_data.csv). **In this spreadsheet, variables `activity.*` are the activity counts for each minute of a 24-hour day starting at midnight.**

* Load, tidy, and otherwise wrangle the data. Your final dataset should include all originally observed variables and values; have useful variable names; include a weekday vs weekend variable; and encode data with reasonable variable classes. Describe the resulting dataset (e.g. what variables exist, how many observations, etc). 
* Traditional analyses of accelerometer data focus on the total activity over the day. Using your tidied dataset, aggregate accross minutes to create a total activity variable for each day, and create a table showing these totals. Are any trends apparent?
* Accelerometer data allows the inspection activity over the course of the day. Make a single-panel plot that shows the 24-hour activity time courses for each day and use color to indicate day of the week. Describe in words any patterns or conclusions you can make based on this graph.



### Optional post-assignment survey

If you'd like, a you can complete [this short survey](https://forms.gle/3BVcBA1ix91oc4Mk9) after you've finished the assignment.