---
title: "Schedule"
---

| Date          | Topic                 | Lecture                                                                      | Slides                                                                           |  Slack                                                                                         | HW                                                         |                        Projects |
|:------------- |:--------------------- |:-----------------------------------------------------------------------------|:--------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------:|:----------------------------------------------------------:| -------------------------------:|
| Tues Sept 3   | What is Data Science? | [What is Data Science?](what_is_ds_i.html)                                   | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_i.pdf)        | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/general)         | [<i class="far fa-file-code fa-lg"></i>](homework_0.html)  |                                 |   
| Thur Sept 5   | Building blocks       | [Best Practices](best_practices.html)                                        | [<i class="fas fa-desktop fa-lg"></i>](slides/best_practices.pdf)                | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CMPF9U6LA)       |                                                            |                                 |
| Tues Sept 10  | Building blocks       | [Writing with Data](writing_with_data.html)                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_with_data.pdf)             | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CMPF9U6LA)       |                                                            |                                 |
| Thur Sept 12  | Building blocks       | [Git](git.html)                                                              | [<i class="fas fa-desktop fa-lg"></i>](slides/git.pdf)                           | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CMPF9U6LA)       | [<i class="far fa-file-code fa-lg"></i>](homework_1.html)  |                                 |   
| Tues Sept 17  | Data Wrangling I      | [Data Import](data_import.html)                                              | [<i class="fas fa-desktop fa-lg"></i>](slides/data_import.pdf)                   | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN898UWNB)      |                                                             |                                 |
| Thur Sept 19  | Data Wrangling I      | [Data Manipulation](data_manipulation.html)                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/data_manipulation.pdf)             | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN898UWNB)      |                                                             |                                 |
| Tues Sept 24  | Data Wrangling I      | [Tidy data](tidy_data.html)                                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/tidy_data.pdf)                     | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN898UWNB)      | [<i class="far fa-file-code fa-lg"></i>](homework_2.html)   |                                 |   
| Thur Sept 26  | Viz + EDA             | [Visualization 1](visualization_pt1.html)                                    | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01ALHR7)      |                                                             |                                 |
| Tues Oct 1    | Viz + EDA             | [Visualization 2](visualization_pt2.html)                                    | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01ALHR7)      |                                                             |                                 |
| Thur Oct 3    | Viz + EDA             | [EDA](exploratory_analysis.html)                                             | [<i class="fas fa-desktop fa-lg"></i>](slides/exploratory_analysis.pdf)          | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01ALHR7)      | [<i class="far fa-file-code fa-lg"></i>](homework_3.html)   |                                 |   
| Tues Oct 8    | Case Study            | [Case study](what_is_ds_ii.html)                                             | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_ii.pdf)       | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CNU5YKBHR)      |                                                             |                                 |
| Thur Oct 10   | Data Wrangling II     | [Reading Data from the Web](reading_data_from_the_web.html)                  | [<i class="fas fa-desktop fa-lg"></i>](slides/reading_data_from_the_web.pdf)     | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN8998SH5)      |                                                             |                                 |
| Tues Oct 15   | Data Wrangling II     | [Strings and Factors](strings_and_factors.html)                              | [<i class="fas fa-desktop fa-lg"></i>](slides/strings_and_factors.pdf)           | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN8998SH5)      |                                                             | [Midterm](midterm_project.html) |
| Thur Oct 17   | Interactivity         | [Making Websites](making_websites.html)                                      | [<i class="fas fa-desktop fa-lg"></i>](slides/making_websites.pdf)               | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN6DF7F1B)      |                                                             |                                 |
| Tues Oct 22   | Interactivity         | [Plot.ly and Dashboards](plotly_and_dashboards.html)                         | [<i class="fas fa-desktop fa-lg"></i>](slides/plotly_and_dashboards.pdf)         | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN6DF7F1B)      | [<i class="far fa-file-code fa-lg"></i>](homework_4.html)   | [Final](final_project.html)     |
| Thur Oct 24   | Iteration             | [Writing Functions](writing_functions.html)                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_functions.pdf)             | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN8KK99NJ)      |                                                             |                                 |
| Tues Oct 29   | Iteration             | [Iteration and Listcols](iteration_and_listcols.html)                        | [<i class="fas fa-desktop fa-lg"></i>](slides/iteration_and_listcols.pdf)        | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN8KK99NJ)      |                                                             |                                 |
| Thur Oct 31   | Iteration             | [Simulation](simulation.html)                                                | [<i class="fas fa-desktop fa-lg"></i>](slides/simulation.pdf)                    | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN8KK99NJ)      | [<i class="far fa-file-code fa-lg"></i>](homework_5.html)   |                                 |
| Tues Nov 5    | -Election day-        |                                                                              |                                                                                  |                                                                                               |                                                             |                                 |
| Thur Nov 7    | Linear models         | [Linear Models](linear_models.html)                                          | [<i class="fas fa-desktop fa-lg"></i>](slides/linear_models.pdf)                 | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN6D894NL)      |                                                             |                                 |
| Tues Nov 12   | Linear models         | [Cross Validation](cross_validation.html)                                    | [<i class="fas fa-desktop fa-lg"></i>](slides/cross_validation.pdf)              | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN6D894NL)      |                                                             |                                 |
| Thur Nov 14   | Linear models         | [Bootstrapping](bootstrapping.html)                                          | [<i class="fas fa-desktop fa-lg"></i>](slides/bootstrapping.pdf)                 | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN6D894NL)      | [<i class="far fa-file-code fa-lg"></i>](homework_6.html)   |                                 |
| Tues Nov 19   | Extra topics          | Building R Packages (with [Emily Robinson](https://twitter.com/robinson_es)) | [<i class="fas fa-desktop fa-lg"></i>](bit.ly/nyrconf19)                         | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01H0GHX)      |                                                             |                                 |
| Thur Nov 21   | Extra topics          | [Shiny](shiny.html)                                                          | [<i class="fas fa-desktop fa-lg"></i>](slides/shiny.pdf)                         | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01H0GHX)      |                                                             |                                 |
| Tues Nov 26   | Extra topics          | [Statistical Learning](stat_learning.html)                                   | [<i class="fas fa-desktop fa-lg"></i>](slides/stat_learning.pdf)                 | [<i class="fab fa-slack fa-lg"></i>](https://p8105fall2019.slack.com/messages/CN01H0GHX)      | [<i class="far fa-file-code fa-lg"></i>](homework_7.html)   |                                 |
| Thur Nov 28   | -Thanksgiving-        |                                                                              |                                                                                  |                                                                                               |                                                             |                                 |
| Tues Dec 3    | -Final Project Week-  |                                                                              |                                                                                  |                                                                                               |                                                             |                                 |
| Thur Dec 5    | -Final Project Week-  |                                                                              |                                                                                  |                                                                                               |                                                             |                                 |
| Tues Dec 10   | Final Projects!       | [What is Data Science Revisited](what_is_ds_iii.html)                        | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_iii.pdf)      |                                                                                               |                                                             |                                 |

